export const AUDIT_EVENTS_TABLE = "security_audit_events"
export const D1_MIGRATIONS_TABLE = "d1_migrations"

export const BACKUP_OBJECT_PREFIX = "d1"
export const BACKUP_OBJECT_SUFFIX = ".sql"
export const BACKUP_FORMAT_VERSION = "2"

export const BACKUP_STORAGE_SOFT_LIMIT_BYTES = 8_000_000_000
export const BACKUP_STORAGE_HARD_LIMIT_BYTES = 9_000_000_000
export const BACKUP_SINGLE_OBJECT_MAX_BYTES = 5 * 1_024 * 1_024 * 1_024

export const D1_EXPORT_MAX_POLL_DURATION_MS = 15 * 60 * 1_000
export const D1_EXPORT_POLL_INTERVAL_MS = 55_000
export const D1_EXPORT_MAX_POLL_OBSERVATIONS = 15

export const D1_EXPORT_START_STEP_MAX_ATTEMPTS = 1
export const D1_EXPORT_POLL_STEP_MAX_ATTEMPTS = 2
export const D1_EXPORT_UPLOAD_STEP_MAX_ATTEMPTS = 2

export const DATABASE_BACKUP_MAX_DURATION_MS = 30 * 60 * 1_000
export const DATABASE_BACKUP_UPLOAD_STEP_TIMEOUT_MS = 15 * 60 * 1_000
export const DATABASE_BACKUP_LEASE_COMMIT_GUARD_MS =
  DATABASE_BACKUP_UPLOAD_STEP_TIMEOUT_MS + 60 * 1_000
export const DATABASE_BACKUP_LEASE_DURATION_MS =
  DATABASE_BACKUP_MAX_DURATION_MS + DATABASE_BACKUP_LEASE_COMMIT_GUARD_MS
